logging:
  level:
    ROOT: INFO
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.ba.bvm.admin: DEBUG
    org.springframework.web: ERROR
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true

  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
    encoding: UTF-8

  thymeleaf:
    cache: false

  datasource:
    type: oracle.jdbc.pool.OracleDataSource
    url: jdbc:oracle:thin:@*:1521/*
    username: *
    password: *
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    #jdbc:
    #  time_zone: Asia/Tokyo

server:
  port: 9800

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is disabled by default on microservices, as you should access them through a gateway.
  # If you want to enable it, please uncomment the configuration below.
  #  cors:
  #    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
  #    allowed-origins: 'http://localhost:9200/,http://localhost:4500/,http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
  #    # Enable CORS when running in GitHub Codespaces
  #    allowed-origin-patterns: 'https://*.githubpreview.dev'
  #    allowed-methods: '*'
  #    allowed-headers: '*'
  #    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
  #    allow-credentials: true
  #    max-age: 1800
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000

next:
  telemetry:
    jaeger-url: http://localhost:4317
  url:
    incident-info: http://localhost:9500/api/v1/vehicle_incident_info
    mock-data: false
    incident-info-yamato: https://your-domain/api-endpoint
    incident-info-yamato-tracking: http://localhost:9500/vehicleIncidentInfo/tracking
    track-by-sip-ttmi: https://your-domain/api-endpoint
    login-system: http://localhost:9800/auth/client
    login-data: "{\"clientId\": \"******\", \"clientSecret\": \"******\"}"
    verify-token: http://localhost:9700
  ttmi:
    token-url: https://your-domain/api-endpoint
    client-id: *
    client-secret: *
    tenant-id: *
  auth-white:
    apis:
      - "/actuator/**"
      - "/v3/api-docs"
      - "/api/v1/vehicle_incident_info"
      - "/metrics"
      - "/auth/login"
      - "/auth/client"
      - "/auth/refresh"
      - "/api/v1/zl_web/**"