logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.ba.bvm.admin: DEBUG
    org.springframework.web: ERROR
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true

  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
    encoding: UTF-8

  thymeleaf:
    cache: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://*:5432/*?currentSchema=staging&allowPublicKeyRetrieval=true&useSSL=false
    username: *
    password: *
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: staging
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: staging
      #jdbc:
      #  time_zone: Asia/Tokyo
server:
  port: 9100

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is disabled by default on microservices, as you should access them through a gateway.
  # If you want to enable it, please uncomment the configuration below.
  #  cors:
  #    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
  #    allowed-origins: 'http://localhost:9200/,http://localhost:4500/,http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
  #    # Enable CORS when running in GitHub Codespaces
  #    allowed-origin-patterns: 'https://*.githubpreview.dev'
  #    allowed-methods: '*'
  #    allowed-headers: '*'
  #    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
  #    allow-credentials: true
  #    max-age: 1800
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000

next:
  url:
    verify-token: https://your-domain/api-endpoint
    domain-carrier: https://your-domain/api-endpoint
    domain-shipper: https://your-domain/api-endpoint
    carrier-link-insert-carrier-order-id-sale: https://your-domain/api-endpoint
    carrier-link-insert-carrier-order-id-sale-cancel: https://your-domain/api-endpoint
    ix-service-shipper-operations-plans: https://your-domain/api-endpoint
    ix-service-shipper-operations-plans-propose: https://your-domain/api-endpoint
    ix-service-shipper-operations-plans-propose-reply: https://your-domain/api-endpoint
    ix-service-shipper-operations-plans-propose-update: https://your-domain/api-endpoint
    ix-service-carrier-transaction-shipper-id-approval: https://your-domain/api-endpoint
    ix-service-carrier-transaction-shipper-id: https://your-domain/api-endpoint
    ix-service-carrier-transaction-shipper: https://your-domain/api-endpoint
    ix-service-carrier-operations-plans: https://your-domain/api-endpoint
    carrier-link-insert-shipper-order-id-sale: https://your-domain/api-endpoint
    cologi-ix-service-operation-request: https://your-domain/api-endpoint
    cologi-ix-service-shipper-operations-plans: https://your-domain/api-endpoint
    domain-ix: https://your-domain/api-endpoint
    domain-ix-demand: https://your-domain/api-endpoint
    domain-gateway: https://your-domain/api-endpoint
    cologi-ix-service-operation-request-new: https://your-domain/api-endpoint
    cologi-ix-service-shipper-operations-plans-propose-reply: https://your-domain/api-endpoint
    cologi-ix-service-shipper-operations-plans-propose-update: https://your-domain/api-endpoint
    cologi-ix-service-shipper-operations-plans-propose: https://your-domain/api-endpoint
    cologi-ix-service-operation-request-handover: https://your-domain/api-endpoint
    ttmi: https://your-domain/api-endpoint
  telemetry:
    jaeger-url: https://your-domain/api-endpoint
  data-common:
    domainGateway: https://your-domain/api-endpoint
  auth-white:
    apis:
      - "/actuator/**"
      - "/v3/api-docs"
      - "/metrics"
      - "/api/v1/matching/**"
      - "/api/v1/trip/**"
      - "/api/v1/trip/trans_order/**/tracking/**"
  mail:
    host: "******"
    port: 587
    password: "******"
    username: "******"
    protocol: "smtp"
    auth: "true"
    startTLS: "true"
    from: "******"
